[package]
name = "ex_attr_nif"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "ex_attr_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.33.0"
xattr = "1.3.1"
rustix = "0.38"
